### ISSUE TITLE
Tenants with MembershipRebootUserService

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/Thinktecture.IdentityServer3.MembershipReboot#10]
I saw that tenants are now supported through the login_hint parameter (#39, #347, #348) and I'm able to successfully pass the tenant property to the server.  However the default MembershipRebootUserService doesn't support it.  Might I suggest the following minor change to the AuthenticateLocalAsync:

            var tenant = string.IsNullOrWhiteSpace(message.Tenant) ? userAccountService.Configuration.DefaultTenant : message.Tenant;
            if (userAccountService.Authenticate(tenant, username, password, out account))

The technique may have to be carried over to some of the other methods, but I think in principle this would complete the multi-tenant support.

Thoughts?

**Comment by brockallen** [comment]
Ok, yes, sorry for the delay. I'll add this.

**Comment by brockallen** [comment]
Done on dev -- mind checking to see if it works for you. Thx.

**Comment by brockallen** [comment]
Ok, I also added it to the external authentication bits.

**Comment by barefootdeveloper** [comment]
Do we think it would be possible to make it so that the user can pass in the tenant they want to log in to as a third field along with their username or password?  The approach that we're taking here doesn't seem to allow that.

**Comment by brockallen** [comment]
IdentityServer won't know to prompt for that, so no. But you can overload the semantics of the username field such that it includes the tenant (e.g. tenant\username like AD does). And in the MembershipRebootUserAccountService there's a virtual called `ValidateLocalCredentials` that you can override to crack the username into the tenant and real username and get the user authenticated however you want. It could also be email, for example, instead of username.

**Comment by barefootdeveloper** [comment]
That's a good idea, I'll explore that path.

**Comment by brockallen** [comment]
Also, another idea is that the client app can pass the tenant via the acr_values param in the request (https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/endpoints/authorization.html). The MR implementation (via this issue) now knows how to use that param.

**Comment by stevenfirstrowinc** [comment]
To test this I'm running the source directly.  I've added my own client and point my application to this instance.  When I get to the login screen the tenant parameter shows up in the username field.  See image.

![capture](https://cloud.githubusercontent.com/assets/7965187/5849742/54ac71e2-a1af-11e4-9e86-e5b028275097.PNG)

**Comment by brockallen** [comment]
Yes, we made a change recently. See the (updated) docs (specifically `login_hint` and `acr_values`):

https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/endpoints/authorization.html

**Comment by stevenfirstrowinc** [comment]
I totally missed that when you mentioned it earlier.  I'll test again today.

**Comment by stevenfirstrowinc** [comment]
I corrected my url and everything seems to go to the right methods and the args are being put in the right place etc.  I am not setup with a database using EF though so the actual authentication call failed.  It will take me a bit of time setup a more thorough test, but as I say all the arguments are coming through where I was expecting them.

If you want to leave this open for a bit longer for me to test I will get to it over the weekend; otherwise you can close and I'll open a new one for any issues I find.

**Comment by brockallen** [comment]
Sure, no problem. Once you're satisfied, then go ahead and close the issue.

**Comment by sherland** [comment]
The link above gives a 404, but this one is currently working:
https://identityserver.github.io/Documentation/docs/endpoints/authorization.html

**Comment by brockallen** [comment]
@sherland yes, we moved github repos, so the old docs links won't work. you have the right one now.
