### ISSUE TITLE
Add user - with code

### ISSUE THREAD

**Issue by pircjernej** [IdentityServer/Thinktecture.IdentityServer3.MembershipReboot#18]
I change Startup.cs with:

            app.Map("/admin", adminApp =>
            {
                var factory = new IdentityManagerServiceFactory();
                factory.Configure(connectionString);

                adminApp.UseIdentityManager(new IdentityManagerOptions
                {
                    Factory = factory
                });
                
            });

            // --- Start custom code ---
            app.Map("/register", builder => builder.Run(context =>
            {
                var qs = context.Request.QueryString.Value;
                var user = parseUserName(qs);
                var pass = parseEmail(qs);
                // ?? missing code  
                var task = context.Response.WriteAsync("User Added");
                return task;
            }));
            // --- end code ----

How can I access functions for adding user to database in missing code part?
For example calling:
https://localhost:44333/core/register?user=jernej&email=test@domain.com&pass=mypass

**Comment by brockallen** [comment]
First of all, your HTTP call could have side effects given that it do this via a GET, which is incorrect.
Second, at that point you just need access to the MR DB -- look at the samples in the MR repo for that. You need a repository and a MR user account service. They have APIs. In fact there are *some* docs here:

https://github.com/brockallen/BrockAllen.MembershipReboot/wiki

**Comment by pircjernej** [comment]
Thanks 1 googol times.
I am new on MVC so all this code is a little distant for me, but I trying :-)

I know that this is not the way how to do this, but I just need some starting push tu understand,
how to add data to database with already made code.

I learn a lot last 10 days...

So the solution for
// ? missing code

<pre>
                var ur = new CustomUserRepository(new CustomDatabase("MembershipReboot"));
                var uas = new CustomUserAccountService(new CustomConfig(), ur);
                uas.CreateAccount("user", "pass", "email");
</pre>

**Comment by brockallen** [comment]
Yea, something like that (except you might be missing a call to `Dispose` on the DB object).
