### ISSUE TITLE
IncludeAllClaimsForUser support

### ISSUE THREAD

**Issue by iMacTia** [IdentityServer/Thinktecture.IdentityServer3.MembershipReboot#9]
I've already discussed with @leastprivilege about this in [this issue](https://github.com/thinktecture/Thinktecture.IdentityServer.v3/issues/621).
Because it came out this is a `Thinktecture.IdentityServer.v3.MembershipReboot` problem, I'm reporting it here.
I also thought to make a pull request, but it doesn't worth it because is just a simple fix of one line (as far as I can see, at least).
Specifically, as @leastprivilege pointed out, the problem seems to be in the `GetProfileDataAsync` function (MembershipRebootUserService.cs: row 55). It should manage the case in which an empty list is passed as parameter for `requestedClaimTypes`. This would add the support for the new property `IncludeAllClaimsForUser` of IdentityServer.v3 scopes.

Thanks in advance

**Comment by brockallen** [comment]
Done on the dev branch. Can you please confirm that it's now working for you? Thx.

**Comment by iMacTia** [comment]
Thanks,
I'll try again with the updated dev branch and let you know.
